name: first github actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting Repositories"

      - name: Run test
        run: echo "Test running..."

  build-and-push-ecr-image:
    name: Build and Push Docker Image to ecr
    needs: integration
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configuration AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090899139254:role/GitHubActionsECRRole
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ secrets.AWS_ECR_LOGIN_URI }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ECR_LOGIN_URI }}/$ECR_REPOSITORY:$IMAGE_TAG

  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configuration AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090899139254:role/GitHubActionsECRRole
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to Amazon ECR 
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull latest images
        run: |
         docker pull ${{ secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME}}:latest

      - name: Stop and remove existing container (if running)
        run: |
         docker ps -q --filter "name=diabetes" | grep -q . && docker stop diabetes && docker rm -fv diabetes || true

      - name: Run Docker Image to serve users
        run: |
         docker run -d -p 8000:8000 --name=diabetes ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_ECR_REPOSITORY_NAME}}:latest

      - name: Clean unused Docker resources
        run: |
         docker system prune -f